Added TP01
UPB-FILS-SdE2/upb-fils-sde2.github.io pull request #17
Opened 2024-02-25 11:18 UTC by Cristiana959

### Pull Request Overview

This pull request adds TP01.

### Testing Strategy

N/A

### TODO or Help Wanted

N/A

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Cristiana Andrei cristiana.andrei@wyliodrin.com

2024-02-25 11:31 UTC, alexandruradovici requested changes
Add the java data types comparison similar to https://embedded-rust-101.wyliodrin.com/docs/lab/00

2024-02-25 11:57 UTC, Cristiana959 commented on docs/tp/01.md
> +
Done

2024-02-25 12:31 UTC, alexandruradovici requested changes

2024-02-25 12:31 UTC, alexandruradovici commented on docs/tp/01.md
> + 2. Tour of Rust [ici](https://tourofrust.com/)
```suggestion
 2. [Tour of Rust](https://tourofrust.com/) tutoriel étape par étape
```

2024-02-25 12:31 UTC, alexandruradovici commented on docs/tp/01.md
> + 1. The Rust Programming Language, Chapitre 1, 2, 3 et 5 [en](https://doc.rust-lang.org/book/#the-rust-programming-language) et [fr](https://jimskapt.github.io/rust-book-fr/)
```suggestion
 1. The Rust Programming Language, Chapitre [1](https://jimskapt.github.io/rust-book-fr/ch01-00-getting-started.html), [2](https://jimskapt.github.io/rust-book-fr/ch02-00-guessing-game-tutorial.html), [3](https://jimskapt.github.io/rust-book-fr/ch03-00-common-programming-concepts.html) et [5](https://jimskapt.github.io/rust-book-fr/ch05-00-structs.html) ([version anglaise](https://doc.rust-lang.org/book/#the-rust-programming-language))
```

2024-02-25 12:31 UTC, alexandruradovici commented on docs/tp/01.md
> +| Length              | Signed | Unsigned | Java Equivalent |
```suggestion
| Longueur              | Signé | Non signé | Équivalent en Java |
```

2024-02-25 12:31 UTC, alexandruradovici commented on docs/tp/01.md
> +| Length              | Floating point | Java Equivalent|
```suggestion
| Longueur              | Virgule flottante | Équivalent en Java |
```

2024-02-25 12:31 UTC, alexandruradovici commented on docs/tp/01.md
> +:::tip
```suggestion
:::info
```

2024-02-25 12:31 UTC, alexandruradovici commented on docs/tp/01.md
> +Pour comprendre mieux, lire le **chapitre 3** qui se trouve dans la **documentation** au début du TP!
```suggestion
Pour comprendre mieux, lire le [chapitre 3](https://jimskapt.github.io/rust-book-fr/ch03-00-common-programming-concepts.html) qui se trouve dans la documentation au début du TP!
```

2024-02-25 12:31 UTC, alexandruradovici commented on docs/tp/01.md
> +:::tip
```suggestion
:::note
```

2024-02-25 12:31 UTC, alexandruradovici commented on docs/tp/01.md
> +:::tip
```suggestion
:::note
```

2024-02-25 12:31 UTC, alexandruradovici commented on docs/tp/01.md
> +Pour comprendre mieux, lire le **chapitre 3** qui se trouve dans la documentation au début du TP!
```suggestion
:::note
Pour comprendre mieux, lire le [chapitre 3](https://jimskapt.github.io/rust-book-fr/ch03-00-common-programming-concepts.html) qui se trouve dans la documentation au début du TP!
```

2024-02-25 12:31 UTC, alexandruradovici commented on docs/tp/01.md
> +Pour comprendre mieux, lire le **chapitre 3** qui se trouve dans la **documentation** au début du TP!
```suggestion
:::info
Pour comprendre mieux, lire le [chapitre 3](https://jimskapt.github.io/rust-book-fr/ch03-00-common-programming-concepts.html) qui se trouve dans la documentation au début du TP! 
```

2024-02-25 12:31 UTC, alexandruradovici commented on docs/tp/01.md
> +Pour comprendre mieux, lire le **chapitre 3** qui se trouve dans la **documentation** au début du TP!
```suggestion
:::note
Pour comprendre mieux, lire le [chapitre 3](https://jimskapt.github.io/rust-book-fr/ch03-00-common-programming-concepts.html) qui se trouve dans la documentation au début du TP!
```

2024-02-25 12:31 UTC, alexandruradovici commented on docs/tp/01.md
> +Pour comprendre mieux, lire le **chapitre 3** qui se trouve dans la documentation au début du TP!
```suggestion
:::note
Pour comprendre mieux, lire le [chapitre 3](https://jimskapt.github.io/rust-book-fr/ch03-00-common-programming-concepts.html) qui se trouve dans la documentation au début du TP!
```

2024-02-25 12:31 UTC, alexandruradovici commented on docs/tp/01.md
> +:::tip
```suggestion
:::warning
```

2024-02-25 12:31 UTC, alexandruradovici commented on docs/tp/01.md
> +Pour comprendre mieux, lire le **chapitre 5** qui se trouve dans la **documentation** au début du TP!
```suggestion
:::note 
Pour comprendre mieux, lire le [chapitre 5](https://jimskapt.github.io/rust-book-fr/ch05-00-structs.html) qui se trouve dans la documentation au début du TP!
```

2024-02-25 12:31 UTC, alexandruradovici commented on docs/tp/01.md
> +
Add details about `match` similar to https://embedded-rust-101.wyliodrin.com/docs/lab/00#match.

2024-02-25 12:31 UTC, alexandruradovici commented on docs/tp/01.md
> +On doit acceder a la directeur ou le fichier main.rs se trouve et executee la comande:
This can be run anywhere from the crate's folder.

In order to run the program we may be anywhere in the crate's folder and execute the command.

2024-02-25 12:31 UTC, alexandruradovici commented on docs/tp/01.md
> +### Exercises
```suggestion
### Exercises

::tip
Si Rust n'est pas installé, vous pouvez utiliser [Rust Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021) pour résoudre les sujets.
::
```

2024-02-25 12:31 UTC, alexandruradovici commented on docs/tp/01.md
> +:::tip
```suggestion
:::note
```

2024-02-25 12:31 UTC, alexandruradovici commented on docs/tp/01.md
> +Hint: Hint: utilisez [io::stdin().read_line(&mut buffer)](https://doc.rust-lang.org/std/io/fn.stdin.html) pour lire a partir du clavier.
```suggestion
:::tip
Utilisez [io::stdin().read_line(&mut buffer)](https://doc.rust-lang.org/std/io/fn.stdin.html) pour lire a partir du clavier.
```

2024-02-25 12:31 UTC, alexandruradovici commented on docs/tp/images/integer.png
I think we can delete this file.

2024-02-25 12:54 UTC, alexandruradovici requested changes

2024-02-25 12:54 UTC, alexandruradovici commented on docs/tp/01.md
>  sidebar_position: 2
```suggestion
sidebar_position: 1
```

2024-02-25 13:28 UTC, alexandruradovici requested changes

2024-02-25 13:28 UTC, alexandruradovici commented on docs/tp/01.md
> +Avant d'aborder les exercices, jetez un œil et parcourez les chapitres [1](https://tourofrust.com/chapter_1_en.html), [2](https://tourofrust.com/chapter_2_en.html) et [3](https://tourofrust.com/chapt
I would use the links for the french version of tour of rust.

2024-02-25 21:50 UTC, alexandruradovici approved these changes

2024-02-25 21:51 UTC, alexandruradovici requested changes
Please change the tour of rust links to the french version.

2024-02-26 10:42 UTC, Ioan-Cristian commented on docs/tp/01.md
> +Tout d'abord, vous n'êtes pas autorisé à utiliser `mut` avec des constantes. Les constantes ne sont pas seulement immuables par défaut, elles sont toujours immuables. Vous déclarez des constantes en
À mon avis, la grande différence entre les variables marquées par `const` et celles marquées par `let` c'est la suivante : les variables `const` sont des variables dont la valeur doit être connue à la compilation à la différence des variables `let` dont la valeur est déterminée au moment de l'exécution du programme (ignorons les optimisations de compilateur qui pourraient faire en sorte que même la valeur des variables `let` peut être connue à la compilation). La marque `const` de Rust est à peu près équivalente à `constexpr` de C++ (la nouvelle norme de C, C2x a également introduit le marqueur `constexpr`). J'ignore les différences de nuance entre les deux.

2024-02-26 10:42 UTC, Ioan-Cristian commented on docs/tp/01.md
> +**Virgule flottante** → Les types à virgule flottante de Rust sont f32 et f64, qui ont respectivement une taille de 32 bits et 64 bits. Le type par défaut est **f64** car sur les processeurs modernes
```suggestion
**Virgule flottante** → Les types à virgule flottante de Rust sont f32 et f64, qui ont respectivement une taille de 32 bits et 64 bits. Le type par défaut est **f64** car sur les processeurs modernes, les calculs utilisant f64 ont à peu près la même vitesse que f32, mais sont plus précis. Tous les types à virgule flottante sont **signés**.
```

2024-02-26 10:42 UTC, Ioan-Cristian commented on docs/tp/01.md
> +Nous définissons une fonction dans Rust en entrant *fn* suivi d'un nom de fonction et d'un ensemble de parenthèses. Les accolades indiquent au compilateur où commence et se termine le corps de la fon
```suggestion
Nous définissons une fonction dans Rust en tapant *fn* suivi d'un nom de fonction et d'un ensemble de parenthèses. Les accolades indiquent au compilateur où commence et se termine le corps de la fonction.
```

2024-02-26 10:42 UTC, Ioan-Cristian commented on docs/tp/01.md
> +#### Parametres
```suggestion
#### Paramètres
```

2024-02-26 10:42 UTC, Ioan-Cristian commented on docs/tp/01.md
> +Toutes les expressions `if` commencent par le mot-clé `if`, suivi d'une condition. Facultativement, nous pouvons également inclure une expression `else`.
```suggestion
Toutes les expressions `if` commencent par le mot-clé `if`, suivies d'une condition. Facultativement, nous pouvons également inclure une expression `else`.
```

2024-02-26 10:42 UTC, Ioan-Cristian commented on docs/tp/01.md
> +Pour comprendre mieux, lire le [chapitre 3](https://jimskapt.github.io/rust-book-fr/ch03-00-common-programming-concepts.html) qui se trouve dans la documentation au début du TP!
```suggestion
Pour en savoir plus, lisez le [chapitre 3](https://jimskapt.github.io/rust-book-fr/ch03-00-common-programming-concepts.html) qui se trouve dans la documentation au début du TP!
```

2024-02-26 10:42 UTC, Ioan-Cristian commented on docs/tp/01.md
> +Les **structures** sont similaires aux tuples, en ce sens qu'elles contiennent les deux plusieurs valeurs liées. Comme les tuples, les morceaux d'une structure peuvent être de différents types. Contr
```suggestion
Les **structures** sont similaires aux tuples : elles contiennent tous les deux plusieurs valeurs liées. Comme les tuples, les parties composantes d'une structure peuvent avoir de différents types. Contrairement aux tuples, dans une structure, vous **nommez** chaque élément de données afin que la signification des valeurs soit claire.
```

2024-02-26 10:42 UTC, Ioan-Cristian commented on docs/tp/01.md
> +Pour utiliser une structure après l'avoir définie, nous créons une **instance** de cette structure en spécifiant des valeurs concrètes pour chacun des champs. Nous créons une instance en indiquant le
```suggestion
Pour utiliser une structure après l'avoir définie, nous créons une **instance** de cette structure en spécifiant des valeurs concrètes pour chacun des champs. Nous créons une instance en indiquant le **nom** de la structure, puis ajoutons des accolades contenant des paires **clé : valeur**, où les clés sont les noms des champs et les valeurs sont les données que nous voulons stocker dans ces champs.
```

2024-02-26 10:42 UTC, Ioan-Cristian commented on docs/tp/01.md
> +Pour comprendre mieux, lire le [chapitre 5](https://jimskapt.github.io/rust-book-fr/ch05-00-structs.html) qui se trouve dans la documentation au début du TP!
```suggestion
Pour en savoir davantage, lisez le [chapitre 5](https://jimskapt.github.io/rust-book-fr/ch05-00-structs.html) qui se trouve dans la documentation au début du TP!
```

2024-02-26 10:42 UTC, Ioan-Cristian commented on docs/tp/01.md
> +Comment définir une énumération :
```suggestion
Définition d'une énumération :
```

2024-02-26 10:42 UTC, Ioan-Cristian commented on docs/tp/01.md
> +Le type `String`, qui est fourni par la bibliothèque standard Rust plutôt que codé dans le langage principal, est un type de chaîne codé en UTF-8 évolutif, mutable et détenu.
*Détenu* veut dire prisonnier. :)

2024-02-26 10:42 UTC, Ioan-Cristian commented on docs/tp/01.md
> +Pour exécuter le programme, nous pouvons être n'importe où dans le dossier de la caisse et exécuter la commande.
Ces deux paragraphes ne disent pas à peu près la même chose ? :)

2024-02-26 10:42 UTC, Ioan-Cristian commented on docs/tp/01.md
> +2. Définissez deux variables et attribuez-leur une valeur numérique. Affiche la valeur maximale entre les deux sans utiliser de variable temporaire.
```suggestion
2. Définissez deux variables et attribuez-leur une valeur numérique. Affichez la valeur maximale entre les deux sans utiliser de variable temporaire.
```

2024-02-26 14:57 UTC, alexandruradovici requested changes

2024-02-26 14:57 UTC, alexandruradovici commented on docs/tp/01.md
> +Avant d'aborder les exercices, jetez un œil et parcourez les chapitres [1](https://tourofrust.com/chapter_1_en.html), [2](https://tourofrust.com/chapter_2_en.html) et [3](https://tourofrust.com/chapt
```suggestion
Avant d'aborder les exercices, jetez un œil et parcourez les chapitres [1](https://tourofrust.com/chapter_1_fr.html), [2](https://tourofrust.com/chapter_2_fr.html) et [3](https://tourofrust.com/chapter_3_fr.html) des tutoriels [Tour of Rust](https://tourofrust.com/00_fr.html).
```

2024-02-26 16:32 UTC, alexandruradovici approved these changes

2024-02-26 16:35 UTC, merged