TP03
UPB-FILS-SdE2/upb-fils-sde2.github.io pull request #24
Opened 2024-03-08 13:19 UTC by Cristiana959

### Pull Request Overview

This pull request adds TP03.

### Testing Strategy

N/A

### TODO or Help Wanted
N/A

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Cristiana Andrei cristiana.andrei@wyliodrin.com

2024-03-08 14:12 UTC, alexandruradovici requested changes

2024-03-08 14:12 UTC, alexandruradovici commented on docs/tp/03.md
> +sidebar_position: 2
```suggestion
sidebar_position: 3
```

2024-03-08 14:12 UTC, alexandruradovici commented on docs/tp/03.md
> +description: Une introduction au langage Rust.
The description is not the right one.

2024-03-08 14:12 UTC, alexandruradovici commented on docs/tp/03.md
> +# TP 02 - Systems de fichiers et le type Result
```suggestion
# TP 03 - Systems de fichiers et le type Result
```

2024-03-08 14:12 UTC, alexandruradovici commented on docs/tp/03.md
> + 1. [Recoverable Errors with Result](https://jimskapt.github.io/rust-book-fr/ch09-02-recoverable-errors-with-result.html)
```suggestion
 1. [Des erreurs récupérables avec Result](https://jimskapt.github.io/rust-book-fr/ch09-02-recoverable-errors-with-result.html)
```

2024-03-08 14:12 UTC, alexandruradovici commented on docs/tp/03.md
> +Le struct *File* renvoie un objet donnant accès à un fichier ouvert sur le système de fichiers.
```suggestion
Le struct `File` renvoie un objet donnant accès à un fichier ouvert sur le système de fichiers.
```

2024-03-08 14:12 UTC, alexandruradovici commented on docs/tp/03.md
> +Les fichiers sont **automatiquement fermés** lorsqu'ils sortent de **scope**. Les erreurs détectées à la fermeture sont ignorées par l'implémentation de Drop. Utilisez la méthode `sync_all` si ces er
```suggestion
Les fichiers sont **automatiquement fermés** lorsqu'ils sortent de **scope**. Les erreurs détectées à la fermeture sont ignorées par l'implémentation de `Drop`. Utilisez la méthode `sync_all` si ces erreurs doivent être gérées manuellement.
```

2024-03-08 15:45 UTC, alexandruradovici approved these changes

2024-03-10 20:03 UTC, alexandruradovici requested changes

2024-03-10 20:03 UTC, alexandruradovici commented on docs/tp/03.md
> +## Le type Result
I would ,ove this before the functions for files, as those functions use it.

2024-03-10 20:03 UTC, alexandruradovici commented on docs/tp/03.md
> +:::note
```suggestion
:::tip
```

2024-03-10 20:06 UTC, alexandruradovici requested changes

2024-03-10 20:06 UTC, alexandruradovici commented on docs/tp/03.md
> +2. Écrivez un programme qui reçoit en argument de ligne de commande un fichier et une tâche. Mettre en œuvre les tâches :
```suggestion
2. Écrivez un programme qui reçoit en argument de ligne de commande un fichier et une tâche. Mettre en œuvre les tâches:
```

2024-03-10 20:06 UTC, alexandruradovici commented on docs/tp/03.md
> +    g. **print_buffer** - imprimez le contenu du fichier à l'aide des fonctions open et read.
```suggestion
    1. **print** - imprime le contenu du fichier et le file descriptor
    2. **size** - imprime la taille du fichier'
    3. **owner** - affiche l'utilisateur (uid) et le groupe (gid) du fichier
    4. **mode_number** - affiche le mode (permissions) en numero du fichier
    5. **type** - le type de fichier: dossier, fichier, lien, périphérique caractère, périphérique bloc, …
    6. **mode_text** - affiche le mode (permissions) en text (rwx…) du fichier
    7. **print_buffer** - imprimez le contenu du fichier à l'aide des fonctions open et read.
```

2024-03-11 11:14 UTC, Cristiana959 commented on docs/tp/03.md
> +## Le type Result
Done

2024-03-11 17:52 UTC, alexandruradovici requested changes

2024-03-11 17:52 UTC, alexandruradovici commented on docs/tp/03.md
> +## Le type Result
We still have `Result` for the main function, maybe move it ahead of that?

2024-03-11 21:49 UTC, alexandruradovici requested changes

2024-03-11 21:49 UTC, alexandruradovici commented on docs/tp/03.md
> +## Le type Result
Place before *Travail avec les fichiers en Rust*

2024-03-11 22:12 UTC, alexandruradovici approved these changes

2024-03-11 22:14 UTC, merged