Added TP04 process
UPB-FILS-SdE2/upb-fils-sde2.github.io pull request #31
Opened 2024-03-17 14:10 UTC by Cristiana959

### Pull Request Overview

This pull request adds TP04(process).

### Testing Strategy

N/A

### TODO or Help Wanted

N/A

### Build

- [ ] Ran `npm build`.

### Author

Signed-off-by: Cristiana Andrei cristiana.andrei@wyliodrin.com

2024-03-17 17:50 UTC, alexandruradovici commented on docs/tp/04.md
> +       // Unsafe to use `println!` (or `unwrap`) here. See Safety.
Why?

2024-03-17 19:15 UTC, alexandruradovici requested changes

2024-03-17 19:15 UTC, alexandruradovici commented on docs/tp/04.md
> +       // Unsafe to use `println!` (or `unwrap`) here. See Safety.
Got it, this is valid only in multithreaded software, which is not the case here. You can use `println!`.

2024-03-18 11:35 UTC, Ioan-Cristian commented on docs/tp/04.md
> +* Ils se réfèrent tous les deux à la même description de fichier ouvert et partagent donc les indicateurs de décalage de fichier et d'état de fichier.
```suggestion
* Ils se réfèrent tous les deux au même descripteur de fichier ouvert et partagent donc les indicateurs de décalage de fichier et d'état de fichier.
```

2024-03-18 11:35 UTC, Ioan-Cristian commented on docs/tp/04.md
> +La fonction `execvp()` **remplace** l'image de processus actuelle par une nouvelle image de processus spécifiée par file. La nouvelle image est construite à partir d'un **fichier exécutable** standar
```suggestion
La fonction `execvp()` **remplace** l'image de processus actuelle par une nouvelle image de processus spécifiée par le fichier. La nouvelle image est construite à partir d'un **fichier exécutable** standard appelé le nouveau fichier d'image de processus. Aucun retour n'est effectué car l'image de processus appelante est remplacée par la nouvelle image de processus.
```

2024-03-18 11:35 UTC, Ioan-Cristian commented on docs/tp/04.md
> +1. Créer un programme de sorte que la contenu d'un fichier qui est recu comme premier argument soit **redirigée vers un fichier** reçu en tant que deuxième argument - une fonctionnalité similaire à l
```suggestion
1. Créer un programme de sorte que le contenu d'un fichier qui est reçu comme premier argument soit **redirigée vers un fichier** reçu en tant que deuxième argument - une fonctionnalité similaire à l'utilitaire [cp](https://www.geeksforgeeks.org/cp-command-linux-examples/) de Linux.
```

2024-03-18 11:35 UTC, Ioan-Cristian commented on docs/tp/04.md
> +2. Écrivez un programme qui alloue dynamiquement un String à l'aide de Box. Lisez un texte au clavier et ajoutez-le aux String allouée. Imprimez le String.
```suggestion
2. Écrivez un programme qui alloue dynamiquement un String à l'aide de Box. Lisez un texte depuis le clavier et ajoutez-le à la String allouée. Imprimez le String.
```

2024-03-18 15:16 UTC, alexandruradovici approved these changes

2024-03-18 15:18 UTC, merged