Second Homework Modifications
UPB-FILS-SdE2/upb-fils-sde2.github.io pull request #44
Opened 2024-04-02 20:52 UTC by popescuatopg

### Pull Request Overview

This pull request modifies the 2nd homework's requirements.
- it modifies the `read` command to be in sync with the command found in the actual homework's `api`
- it removes the `DirectoryNotEmpty` error from the `rm` command's requirements, as the `rm` is supposed to be used on only files, not directories

### Testing Strategy

N/A

### TODO or Help Wanted

N/A

### Build

- [x] Ran `npm build`.

### Author

Signed-off-by: Adrian Popescu <adrian.popescu1005@stud.fils.upb.ro>

2024-04-02 21:25 UTC, alexandruradovici requested changes

2024-04-02 21:25 UTC, alexandruradovici commented on docs/devoir/02.md
> +2. `PermissionDenied` si le répertoire parent ne dispose pas d'autorisations en écriture
This should stay as it was.

2024-04-02 22:24 UTC, popescuatopg commented on docs/devoir/02.md
> +2. `PermissionDenied` si le répertoire parent ne dispose pas d'autorisations en écriture
Rolled back to its previous state

2024-04-03 06:28 UTC, alexandruradovici approved these changes

2024-04-03 06:30 UTC, merged